# fly.toml app configuration file generated for threadwave on 2023-10-01T13:42:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "threadwave"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
